### ISSUE TITLE
REQ: TWRP 3.2.3 support (with OTA fix for encrypted devices & MD5 support but keep SuperSU)

### ISSUE THREAD

**Issue by FreshhhHub** [mracar07/android_device_zuk_z2_row#1]
Hi, could you please add TWRP 3.2.3 support in ZUK_Z2_ROW Red Wolf unofficial ?  
Thanks a lot in advance!!  
All the best.  

TWRP 3.2.3 Custom Recovery – Changelog:TWRP 3.2.3 Custom Recovery – Changelog:

As stated, TWRP 3.2.3 is an iterative release, it carries enough feature enhancements and changes making it a eligible for a new version number.

•Fix automatic installing of OTA zips on encrypted devices
•Remove SuperSU from TWRP
•Support both md5 and md5sum file extensions when doing MD5 checking for zip files

**Comment by mracar07** [comment]
@FreshhhHub Wtf

**Comment by mracar07** [comment]
https://forum.xda-developers.com/showpost.php?p=77672365&postcount=43

Updated.
